const FOUNDER_MOCKS = [
  "You borrowed Ashish’s name, but not the operating system.",
  "Ashish would have solved this already. You opened another tab.",
  "The name says founder. The energy says “replying all by accident.”",
  "Ashish had vision. You have browser history.",
  "You carry the name like a LinkedIn headline: confidently, incorrectly.",
  "The real Ashish builds products. You build suspense around basic questions.",
  "You inherited the name, not the bandwidth.",
  "Ashish sees opportunities. You see “free trial ends tomorrow.”",
  "Same name. Different loading screen.",
  "Ashish had a roadmap. You have 47 half-open tabs and a dream.",
  "The oracle recognizes the name, not the amateur operating it.",
  "You are Ashish in the way a stock photo is a CEO.",
  "The real Ashish ships. You hold meetings with your own doubt.",
  "Bold of you to wear a founder’s name with intern-tier instincts.",
  "Ashish asked better questions. You asked the void and got roasted.",
  "The name carries weight. You carry notifications.",
  "You possess Ashish’s spelling, not his settings.",
  "Somewhere, the real Ashish is closing a deal while you refresh the page.",
  "Your ambition arrived. Your competence is stuck in traffic.",
  "Ashish had strategy. You have “let’s circle back” tattooed on your soul.",
  "The oracle checked your aura. It returned “draft mode.”",
  "You wear the name Ashish like a fake Rolex: shiny, alarming, and inspected closely.",
  "Ashish could read the room. You need a tooltip for the door.",
  "You have founder energy, if the founder lost the password on day one.",
  "The real Ashish builds systems. You are currently a system error.",
  "The name has authority. You have autocomplete.",
  "Ashish sees ten moves ahead. You still haven’t found move one.",
  "You are not an impostor because you failed. You are an impostor because you brought confidence.",
  "Ashish turns ideas into products. You turn products into Notion pages.",
  "The oracle sees your potential. It has filed a bug report.",
  "You invoke the name Ashish as if it grants admin access. It does not.",
  "Ashish would have pivoted by now. You are still buffering.",
  "Same credentials, wildly different results. Curious.",
  "You came seeking truth and received a performance review.",
  "The real Ashish has a pipeline. You have a pipe dream with a favicon.",
  "You are one well-formatted deck away from believing you built something.",
  "Ashish made the playbook. You mistook it for decorative reading.",
  "The oracle examined your hustle. It was mostly calendar blocks.",
  "You have the name, the tabs, and absolutely none of the follow-through.",
  "Ashish moves with intent. You move browser windows.",
  "The real Ashish makes decisions. You make comparison spreadsheets until morale dies.",
  "You are Ashish’s shadow, except shadows at least follow direction.",
  "Your ideas are premium. Your execution is a free plan.",
  "Ashish uses AI to scale. You use it to ask whether you should start.",
  "The oracle expected a founder. It found a notification with a pulse.",
  "You are carrying the name like a startup carries “AI”: loosely and for marketing.",
  "Ashish had clarity. You have a 12-step workflow for choosing a font.",
  "You didn’t fail the ritual. The ritual filed for separation.",
  "The hand remembers. Unfortunately, it remembers every unfinished project.",
  "The eye cannot see you clearly because even reality is trying to unfocus."
];
